### ISSUE TITLE
some question about gt

### ISSUE THREAD

**Issue by DoongLi** [KTH-RPL/DynamicMap_Benchmark#1]
Hi Kin, thank you for your good work！I have a question about groudtruth, that is, how are static points and dynamic points generated in gt? Was it hand-marked？

**Comment by Kin-Zhang** [comment]
Yes, for av2 and semindoor, hand-marked
Kitti is for semantic kitti label

**Comment by DoongLi** [comment]
Ok, thx Kin, look forward to your other two work in the review！
