### ISSUE TITLE
如何在线使用

### ISSUE THREAD

**Issue by UpppD7** [KTH-RPL/DynamicMap_Benchmark#10]
非常感谢您的优秀工作，但我仍存在一些疑惑。
在其他平台看见您介绍erasor和removert是离线方案，octomap是在线方案，但未找到关于在线使用的介绍，请问如何在线使用，实时清除动态障碍物？

**Comment by Kin-Zhang** [comment]
奥，因为当时我对于 离线和在线的区分在于是否需要使用prior map；在线的话 不需要准备raw map，可以直接拿到数据就开始做；
如果你说的在线是：希望ROS的实时运行 或者 可视化？我并没有给一个单独的branch，可能call一下这个func在callback里就行？

这里是octomap的方案：https://github.com/Kin-Zhang/octomap/tree/feat/benchmark

**Comment by Kin-Zhang** [comment]
更具体一点，对于可视化和ROS的实时显示：
1. rosbag or open sensor
2. 然后将point cloud传进 run 的func里：`map_updater.run(pcd);` 比如这里传的是pcd，你改成 point cloud msg的data就行
3. 然后实时显示的话 就单独写一个segment 或者 在最后callsavemap

**Comment by UpppD7** [comment]
感谢您的解答！
