### ISSUE TITLE
请问怎么生成逐帧的清理结果

### ISSUE THREAD

**Issue by pointcloud123** [KTH-RPL/DynamicMap_Benchmark#12]
你好 我发现removert代码只提供了全局地图的清理结果pcd文件 请问怎么生成每一帧 即每一个pcd文件的清理结果？

**Comment by Kin-Zhang** [comment]
因为这个benchmark的本意是生成全局地图的清理结果；如果生成逐帧的话 建议自己新加一个function 重新for 所有帧 再单独保存... 具体可以去removert官方那边问一下

**Comment by pointcloud123** [comment]
好的 感谢
