### ISSUE TITLE
问题交流！

### ISSUE THREAD

**Issue by wcyjerry** [KTH-RPL/DynamicMap_Benchmark#13]
Hello 张博，
    我现在其实在做一些点云的数据标注工作，目前想法是参考semantic kitti，去融合多帧的点云，有一个比较麻烦的问题就是动态障碍物的去除上。但是由于场景中的动态障碍物比较少（比如在停车场的场景），可能动态物体只占1%的比例，比如行驶的车、人等，但很少。目前是用了一个MOT的方法去做的动态判断，把多帧的检测结果关联起来，通过阈值来判断是否发生运动，但是这样会比较依赖检测的结果精度。
    就你的经验而言，你觉得我是否应该尝试一下这个repo里的一些专用的动态去除方法呢？

**Comment by Kin-Zhang** [comment]
可能我还需要知道你的需求 是需要 更激进的去掉所有动态点，还是说你希望更保守一点 比如尽可能保留静态点；哪一种更适用你的需求？

**Comment by wcyjerry** [comment]
> 可能我还需要知道你的需求 是需要 更激进的去掉所有动态点，还是说你希望更保守一点 比如尽可能保留静态点；哪一种更适用你的需求？

可能更中和一点，我已经看过你的bilibili视频，选AA比较高的。不过我还有一个疑问：如果一个目标先停止，然后运动，停止那段时间的点云在整个融合的map中会被保留

**Comment by Kin-Zhang** [comment]
> 如果一个目标先停止，然后运动，停止那段时间的点云在整个融合的map中会被保留

对于octomap系列的是的，因为停止时间足够长就能更新占据的概率从而被保留；不过 dufomap 不会，一旦运动过&停止区域被检测为空过，则可以去除，你可以试一下：https://github.com/KTH-RPL/dufomap

**Comment by wcyjerry** [comment]
> > 如果一个目标先停止，然后运动，停止那段时间的点云在整个融合的map中会被保留
> 
> 对于octomap系列的是的，因为停止时间足够长就能更新占据的概率从而被保留；不过 dufomap 不会，一旦运动过&停止区域被检测为空过，则可以去除，你可以试一下：https://github.com/KTH-RPL/dufomap 数据格式和此repo一致，可以先参考此repo进行数据处理后，再运行

OK，dufomap依然不是learning based哈，看到你们还有一篇deeplearning的方法，不过需要ground estimation，我的数据用了一些方法去做ground estimation都不太理想。

**Comment by wcyjerry** [comment]
> > 如果一个目标先停止，然后运动，停止那段时间的点云在整个融合的map中会被保留
> 
> 对于octomap系列的是的，因为停止时间足够长就能更新占据的概率从而被保留；不过 dufomap 不会，一旦运动过&停止区域被检测为空过，则可以去除，你可以试一下：https://github.com/KTH-RPL/dufomap 数据格式和此repo一致，可以先参考此repo进行数据处理后，再运行

C++的代码我确实改起来有点慢，跑自己的数据集没有gt的话 应该也可以吧。

**Comment by Kin-Zhang** [comment]
> 看到你们还有一篇deeplearning的方法

这个其实只是审稿人的comment，希望我们能对比一下learning 方案，但实际上learning方案并不是专门做动态去除，一般是scene flow 光流速度检测 或者是 moving object segmentation 之类的：会出现你说的，如果他运动了一下，然后停止了 就不会被检测了

> 跑自己的数据集没有gt的话 应该也可以吧。

对的，在代码修改 我建议你不用改，而是把自己的bag文件 通过这个script转换一下：https://github.com/KTH-RPL/DynamicMap_Benchmark/blob/master/scripts/README.md#custom-dataset

**Comment by wcyjerry** [comment]
> 对的，在代码修改 我建议你不用改，而是把自己的bag文件 通过这个script转换一下：https://github.com/KTH-RPL/DynamicMap_Benchmark/blob/master/scripts/README.md#custom-dataset
Thanks for your kind and patient response! I will try dufomap and give you some feedbacks!

**Comment by wcyjerry** [comment]
@Kin-Zhang Hello，我在尝试Defomap，实际上我已经有解析好的pcd和pose，但是我试了一下demo的data，里面是没有pose的呀，这个算法不需要pose吗

**Comment by Kin-Zhang** [comment]
**All datasets are integrated into a unified PCD format with point cloud data and pose in it.**

举个例子：
![image](https://github.com/KTH-RPL/DynamicMap_Benchmark/assets/35365764/c20a3940-6e49-4500-bcc8-234e7e27ef81)

**Comment by wcyjerry** [comment]
OK, I see.
再次感谢！
