### ISSUE TITLE
关于实时动态点云滤除建图

### ISSUE THREAD

**Issue by Novak88** [KTH-RPL/DynamicMap_Benchmark#16]
有幸阅读了您解读A Dynamic Points Removal Benchmark in Point Cloud Maps的博客https://www.cnblogs.com/kin-zhang/p/17773537.html，里边您有提到“得益于octomap (c) 方案是唯一的不需要先验原始地图的，也就是后续如果能对时间进行改进 可以做到实时建图，最后直接输出clean map”。请问下，octomap (c) 的代码是method下的octomap吗？您提到的“对时间进行改进可以做到实时建图”怎么理解？

**Comment by Kin-Zhang** [comment]
octomap (c) 是基于octomap 加了noise filter 和ground estimation，具体可以看代码 https://github.com/Kin-Zhang/octomap/tree/feat/benchmark

对时间改进是因为每帧的运行时间还是有2s左右，如果对底层做优化达到100ms的华 就可以做到实时建图了；比如这个方法：https://github.com/KTH-RPL/dufomap

**Comment by Novak88** [comment]
感谢回复

octomap跟dufomap我都做了尝试，dufomap是要快出很多，用提供的数据集都是没问题的。

然后我用自己录的数据，把每帧点云消息转成了pcd后，喂给octomap跟dufomap，运行得到的结果成了一坨图，似乎是坐标系哪里的出了问题。好像是不断地在原点上，不断地加入点云，但实际上雷达是在前行，位姿是在不断变化的。

每帧点云之所以是扇形，是我为了滤除后边手持设备的人，所以值保留了特定角度的点云。

![slam2](https://github.com/user-attachments/assets/f5466ea4-b2a6-4ec0-8edc-f6f258b4ebfc)

**Comment by Kin-Zhang** [comment]
感觉是pose没给到pcd里面？check一下这里的说明：https://kth-rpl.github.io/DynamicMap_Benchmark/data/#format

和这里给了演示如何转换的代码：https://github.com/Kin-Zhang/simple_ndt_slam/blob/master/tools/README.md#extract_pcdfbag_cpp

**Comment by Novak88** [comment]
谢谢，您太热心了。确实是pose信息没有给到，我先自己尝试下，如果遇到问题再向您请教

**Comment by undermoonstealmelon** [comment]
您好！我也遇到了相同的问题，尝试了好多方法都没能解决，请问是否可以将.bag发送给您，肯请得到您的帮助！
