### ISSUE TITLE
有关自定义数据集的问题

### ISSUE THREAD

**Issue by xxxsdxx** [KTH-RPL/DynamicMap_Benchmark#17]
您好，非常感谢您的工作。但是我使用DUFOMap与Octomap w GF在提供的kitt数据集中取得了较好的结果。但是当我使用自己的数据集时，好像并没有起到作用，车辆产生的动态障碍仍然存在。
![road](https://github.com/user-attachments/assets/7023b5bf-50ff-4c20-803c-a35431bec177)
可以看到道路中间由于车辆导致的点云仍然存在，我不清楚为何没有起到作用。我保存的每帧点云的方法为：将每帧点云转换到世界坐标系然后保存下来（因为我发现提供的脚本也是这样做的）。但是最后得到的效果十分不好，请问您有什么建议么。

**Comment by Kin-Zhang** [comment]
我感觉… 你的数据转换出了问题，看起来odom并不正确，方便的话 可以发一下数据 我看一下吗？

**Comment by xxxsdxx** [comment]
您好，实际上我是将每帧点云通过odom变换到世界坐标系然后保存下来，并没有按照文档里说的录制bag，但是我刚才也录制的相应的rosbag包，请问您是想要bag包么，我该如何发给您。

**Comment by xxxsdxx** [comment]
[road.zip](https://github.com/user-attachments/files/16466887/road.zip)
这是这是bag包

**Comment by Kin-Zhang** [comment]
这样吗？如果没有bag包，那能直接把你原始点云和odom 发给我也行

**Comment by xxxsdxx** [comment]
我刚刚录制了一个bag包在上面的压缩文件中，不知道您能看见么。

**Comment by xxxsdxx** [comment]
https://drive.google.com/file/d/1M1gNOZYwZalt7rfDnzl4tiNeQ9vMWQqg/view?usp=drive_link
我将得到的雷达帧与对应的pose(kitti格式)的上传到driver中了，希望您有时间能帮我解答一下

**Comment by Kin-Zhang** [comment]
![image](https://github.com/user-attachments/assets/71bf31dd-2ca7-4f86-97ed-92890d239f43)

我下载了bag包并看了数据，不知道为何你使用的sensor极其稀疏：
1. 每帧只有**4558**个点云，几乎benchmark所有方法都至少需要16线起步LiDAR才能有较多的信息进行去除
2. 整个数据只有300个frame，全部点云加起来都比一阵64线的信息还少...

所以我感觉主要还是数据太稀疏（1% 64LiDAR）导致所有算法都失效了（我几乎快速尝试了benchmark内所有方法）

**Comment by xxxsdxx** [comment]
非常感谢您的尝试，我使用的是雷神16线的雷达。很奇怪，因为我发现我保存的每帧点云实际上的确数目很少，很有可能我的工作环境是高速公路环境，导致采集的点数量极少。总之只要有思路就可以了。再次感谢。

**Comment by Kin-Zhang** [comment]
建议检查一下雷达驱动配置是否正确，因为这不太是个正常的16线雷达的表现效果...

anyway，如果有问题的话，后续可以再留言~
