### ISSUE TITLE
Custom data config

### ISSUE THREAD

**Issue by DarrenWong** [KTH-RPL/DynamicMap_Benchmark#21]
Thanks for the great work! I am evaluating the dynamic object removal using our custom data by a Velodyne HDL 32 (the ground is around -2.2 meters in the LiDAR frame). But the results of dufomap and erasor (use default setting) seem not as good as the KITTI one in the example, can I know if any parameters I can tune? The [data](https://www.dropbox.com/scl/fi/o05pe9z5lh06lrhs0x771/dynamic_data.zip?rlkey=wcgg63f4w4c9ac6u88357mh5k&st=03cq8z7k&dl=0) includes the pcd and the evaluation output is provided for reference. Thanks a lot!

The data: [video](https://www.dropbox.com/scl/fi/y8no1o9wpot63qjxivpqd/video.mp4?rlkey=tdik34wv49ts2zcubzk0837c9&st=6ssera5j&dl=0):
![image](https://github.com/user-attachments/assets/683e3c9a-6060-4737-beb7-04df38290095)

The existing results,

Dufomap: 

numerous vehicle cloud is not removed

![image](https://github.com/user-attachments/assets/76bd6005-5aab-45fe-b09b-da388e7d6a9c)

missing data on the sign, and also some ground points

![9ea4bd7f175cd5df8944da26fc5bb97](https://github.com/user-attachments/assets/95ac11f1-a47a-424f-ab04-d3dbf0672c0b)

**Comment by Kin-Zhang** [comment]
![image](https://github.com/user-attachments/assets/3cea093b-81e4-4907-a9a0-73930b016730)

Thanks for sharing, I checked, it looks like you forgot to save the pose in the `VIEWPOINT` field: https://kth-rpl.github.io/DynamicMap_Benchmark/data/#a-header-example


And here is an example way to save:

https://github.com/Kin-Zhang/simple_ndt_slam/blob/e12840886641b364580f9b5820164b8b849d7899/tools/src/extract_pcdFbag_tf.cpp#L195-L203

```cpp
      // set the viewpoint -> CHECK PCD VIEWPOINT FIELD
      pcl_cloud->sensor_origin_ = Eigen::Vector4f(pose[0], pose[1], pose[2], 0.0); 
      pcl_cloud->sensor_orientation_ = Eigen::Quaternionf(pose[6], pose[3], pose[4], pose[5]); // w, x, y, z


      // save the pcd
      std::ostringstream tmp_filename;
      tmp_filename << save_pcd_folder << "/pcd/" << std::setfill('0') <<
      std::setw(6) << count << ".pcd"; std::string pcd_file =
      tmp_filename.str(); pcl::io::savePCDFileBinary(pcd_file, *pcl_cloud);
```

**Comment by DarrenWong** [comment]
Thanks for your reply! I will re-implement the Pcd write part and evaluate again.

**Comment by DarrenWong** [comment]
Dear Dr. Zhang,

Thanks for your reply. The results are impressive after I regenerate the pcd and put it into testing again using Dufomap. However, some areas especially on the opposite road are not good. Is it possible for you to provide some hits on any parameter I could further turn (default config of Dufomap is used)? The update [data](https://www.dropbox.com/scl/fi/cfjs27ymolqxnk1kdepcz/custom2_data.zip?rlkey=44wc1que6r3b7bbonnqi7jnlj&dl=0) is provided for your reference. Thank you very much for your time!

The update PCD viewpoint using the SLAM pose,
![image](https://github.com/user-attachments/assets/29ea56d8-aa68-4ef6-9468-6366bb2b9987)


The car near the sensor is removed
![image](https://github.com/user-attachments/assets/ea6a417b-51fe-443d-a215-a54286460d78)

For the cars on the opposite road of the vehicle sensor platform has remained

![image](https://github.com/user-attachments/assets/fc41035d-0948-403b-9450-4a7d02fda77e)

**Comment by Kin-Zhang** [comment]
![image](https://github.com/user-attachments/assets/a9761663-eaee-41d9-bd38-8f91e6c850ef)

I checked again and believe this is at the end of the frame, and since the DUFOMap strategy is to build the void(free) map, but the space you show and I pointed out, we don't have enough time/dense info to say that.

And this is one limitation we already mentioned in the [paper Sec V-E](https://arxiv.org/abs/2403.01449):

![image](https://github.com/user-attachments/assets/09942aaa-3136-4aea-b1e1-9125ebf8b3fd)

**Comment by DarrenWong** [comment]
Thanks for your reply!

**Comment by DarrenWong** [comment]
Dear Dr. Zhang, thanks again for your kind support. We will consider involving clustering or integrating with learning-based detection before the fine refinement based on your pipeline. The unexpected dynamic objects are quite challenging for large-scale mapping, especially in dense urban such as Hong Kong. Hopefully, we could have a chance to collaborate on dynamic object removal in the future.
