### ISSUE TITLE
removert中的问题

### ISSUE THREAD

**Issue by JunandTong** [KTH-RPL/DynamicMap_Benchmark#3]
博主你好，我最近也在研究removert方法，看了你的论文还有代码。目前有两个疑问：1.你的代码中将全局地图转化为rangimage的步骤没有将全局地图转化到当前扫描的局部坐标系下。2.我发现你的代码中和removert的原作者一样也没有revert部分，只有remove部分。
能解答一下为什么这样做吗，我最近在补充removert代码中的revert部分。还有就是在你的论文中描述了removert方法的缺点，有什么方法可以改进这些缺点吗。可以结合学习的方法先进行过滤在用removert吗？

**Comment by Kin-Zhang** [comment]
你好，

1. 所有的地图 + scan 在数据处理阶段就已经在全局下了，并不涉及代码内需要再做一次；至于你说的都在局部坐标系，我再次检查了代码
没有问题，参照：map2RangeImg，scan2RangeImg 这两个函数内部都做了 - x_curr (y,z)
了；最后根据KITTI的最终效果和原论文一致 也可以得知代码重构没有问题
2. 因为我是直接fork的commit，具体可以看fork的commit 记录，revert部分原作者并没有在原repo中实现，所以我只是进行重构
不进行其他实现

关于缺点，我们有正在投的两篇论文更为详细的解释和改进，可以继续follow我们的工作~ 两篇在被接受后 均会加入到benchmark 开源给大家

**Comment by Kin-Zhang** [comment]
如果你实现并检查了revert部分，欢迎提出pull request给原作者和我们的fork repo，我们会进行快速的review并合并

**Comment by JunandTong** [comment]
感谢你的解答，期待你更优秀的工作
