### ISSUE TITLE
Is the GT pose relative to the lidar origin?

### ISSUE THREAD

**Issue by msusing** [KTH-RPL/DynamicMap_Benchmark#4]
Thanks for your work. I have no experience using KITTI dataset. It seems the original odometry pose ground truth is for the camera. I wonder if the pose in the pcd is relative to lidar origin? It seems each pcd has been transformed with its pose in its VIEWPOINT field. Looking forward to your reply.

**Comment by Kin-Zhang** [comment]
Yes based on the extract_kitti.py you can know how we do that.

Step mainly already set pose to the LiDAR frame then world frame

Best
Kin

**Comment by msusing** [comment]
Got it. Thank you for your reply.
While reading the scripts, I have another question.
In extract_gtcloud.cpp, it seems the ego points are set to dynamic in the following lines:
 https://github.com/KTH-RPL/DynamicMap_Benchmark/blob/master/scripts/cpp/extract_gtcloud.cpp#L105-L110

I did a quick look for removert in methods. But I didn't find code dealing these ego points. How do you deal with them?
在 2023年11月15日+0800 23:35，Kin ***@***.***>，写道：
> Yes based on the extract_kitti.py you can know how we do that.
>
> Step mainly already set pose to the LiDAR frame then world frame
>
> Best
> Kin
>

**Comment by Kin-Zhang** [comment]
here is another comment mentioned this before: https://github.com/KTH-RPL/DynamicMap_Benchmark/issues/3#issuecomment-1801398070

Following just google translate first part:
All maps + scans are already done globally during the data processing stage, and do not need to be done again in the code. As for what you said are all in the local coordinate system, I checked the code again and there is no problem. Refer to: map2RangeImg, scan2RangeImg. Both functions have done - x_curr (y,z) internally; in the end, according to the final effect of KITTI, which is consistent with the original paper, we can also know that there is no problem with code reconstruction.

**Comment by msusing** [comment]
Sorry but I mean you set near points max_dist_square (3m in the code) as gt dynamic. But in parsing single scan to algorithms or in evaluating code, I did not find the same process. If the algorithms do not mark these near points as dynamic, I think it brings some different on results.

**Comment by Kin-Zhang** [comment]
Not really max_dis_square 3m but also sematic kitti label as unknown which is ego vehicle point. Normally, the method should have the ability to detect these points also.

**Comment by msusing** [comment]
Okay, I will think about it. BTW, your code is very clean and enjoyable to read. Wish you good luck in your scientific research.
在 2023年11月17日+0800 16:46，Kin ***@***.***>，写道：

**Comment by Kin-Zhang** [comment]
Thanks, you too ❤️. Let me know if you have further questions. and stay tuned with us (more methods will come soon)
