### ISSUE TITLE
gt_cloud是如何得到的？

### ISSUE THREAD

**Issue by Jun-creat** [KTH-RPL/DynamicMap_Benchmark#5]
想问一下数据文件中SemanticKITTI数据集的gt_cloud是如何得到的？我暂时没有在您的项目中找到这一点

**Comment by Jun-creat** [comment]
谢谢您的回答！我的理解是(1)您通过extract_semkitti.py将SemanticKITTI的点云由bin转为pcd格式并添加label数据，(2)然后使用extract_gtcloud.cpp程序根据同一物体在两次不同的扫描中得到 相同的 ID（.label文件中的数据低16位，即相同标签代码同一动态物体的点云）来得到gt_cloud。请问我的理解是否正确？

**Comment by Jun-creat** [comment]
![图片1](https://github.com/KTH-RPL/DynamicMap_Benchmark/assets/76730753/d8c27308-3869-4c0b-8240-56af7d5bf23c)
不好意思，我还有一个问题。根据您的代码，使用removert方法对kitti-00数据集进行动态点云滤除，可以发现图中还有两部分密集点云没有去除，好像和readme中的您给出的图片有出入，请问原因是啥，是这个方法自身的原因吗?能否改进

**Comment by Kin-Zhang** [comment]
图片是正常的 方法的局限性，每个方法都不是完美的...

如果感兴趣 可以follow 我们后续的文章，还在审 所以无法公开

**Comment by Kin-Zhang** [comment]
> 谢谢您的回答！我的理解是(1)您通过extract_semkitti.py将SemanticKITTI的点云由bin转为pcd格式并添加label数据，(2)然后使用extract_gtcloud.cpp程序根据同一物体在两次不同的扫描中得到 相同的 ID（.label文件中的数据低16位，即相同标签代码同一动态物体的点云）来得到gt_cloud。请问我的理解是否正确？

这个部分 请参考semantic-kitti的官方文件： https://github.com/PRBonn/semantic-kitti-api/blob/master/config/semantic-kitti-mos.yaml#L33-L41
里面有专门针对moving的label

**Comment by Jun-creat** [comment]
好的，非常感谢！
