### ISSUE TITLE
cmake Error

### ISSUE THREAD

**Issue by GavyndotLee** [KTH-RPL/DynamicMap_Benchmark#7]
Dear Dr. Zhang,

I am writing to express my sincere gratitude for your open-source contributions. I have encountered an issue during the cmake process and am seeking your assistance. The steps I have taken are as follows: cd methods/octomap && cmake -B build. The output was

![image](https://github.com/KTH-RPL/DynamicMap_Benchmark/assets/115397140/69a196ea-9870-42fe-9676-c9ce20c06088)

Yours sincerely.

**Comment by Kin-Zhang** [comment]
looks like glog is not installed:

run this command:

```bash
curl -sL https://raw.githubusercontent.com/Kin-Zhang/Kin-Zhang/main/Dockerfiles/latest_glog_gflag.sh | bash
```

I will update the dockerfile also. thanks for the reminder.

**Comment by Kin-Zhang** [comment]
it looks like glog didn't install, could you use the repo dockerfile to build?

this line will install the glog and gflag things:

https://github.com/KTH-RPL/DynamicMap_Benchmark/blob/a6f6aa615c30d9ab3920a0c157435d9c39af2d13/Dockerfile#L10

**Comment by Kin-Zhang** [comment]
also, a reminder for people may not be familiar with docker, you can always login to docker as root without any password:

check here

https://www.baeldung.com/ops/root-user-password-docker-container
```bash
docker exec -it -u 0 image_name /bin/bash
```

**Comment by GavyndotLee** [comment]
> it looks like glog didn't install, could you use the repo dockerfile to build?
> 
> this line will install the glog and gflag things:
> 
> https://github.com/KTH-RPL/DynamicMap_Benchmark/blob/a6f6aa615c30d9ab3920a0c157435d9c39af2d13/Dockerfile#L10

Dear Dr. Zhang,
Thank you for your response. I used the Dockerfile provided in repo. However, I encountered compilation issues, as shown in the above image(https://github.com/KTH-RPL/DynamicMap_Benchmark/issues/7#issue-2067570241). The https://github.com/KTH-RPL/DynamicMap_Benchmark/blob/a6f6aa615c30d9ab3920a0c157435d9c39af2d13/Dockerfile#L10 command seems to have not worked, because when I run the `whereis glog` command, the output is empty. 
Look forward to your guidance on this matter.
Best regards

**Comment by GavyndotLee** [comment]
> > it looks like glog didn't install, could you use the repo dockerfile to build?
> > this line will install the glog and gflag things:
> > https://github.com/KTH-RPL/DynamicMap_Benchmark/blob/a6f6aa615c30d9ab3920a0c157435d9c39af2d13/Dockerfile#L10
> 
> Dear Dr. Zhang, Thank you for your response. I used the Dockerfile provided in repo. However, I encountered compilation issues, as shown in the above image([#7 (comment)](https://github.com/KTH-RPL/DynamicMap_Benchmark/issues/7#issue-2067570241)). The
> 
> https://github.com/KTH-RPL/DynamicMap_Benchmark/blob/a6f6aa615c30d9ab3920a0c157435d9c39af2d13/Dockerfile#L10
> 
> command seems to have not worked on my machine, because when I run the `whereis glog` command, the output is empty.
> Look forward to your guidance on this matter.
> Best regards

Dear Dr. Zhang,

I am writing to inform you that the issue with the compilation error has been resolved. As indicated by the printout information, my machine indeed lacked the two cmake files. I managed to resolve the issue of missing these two files by installing from the source code. 

Great job and thank you!
